-- Create the Coinbase App Store rank snapshots table
CREATE TABLE IF NOT EXISTS coinbase_app_rank_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captured_at TIMESTAMPTZ DEFAULT now(),
  finance_rank INTEGER,
  overall_rank INTEGER,
  source TEXT
);

-- Create an index for efficient querying by timestamp (newest first)
CREATE INDEX IF NOT EXISTS coinbase_app_rank_snapshots_captured_at_desc 
  ON coinbase_app_rank_snapshots (captured_at DESC);

-- Add a comment to the table for documentation
COMMENT ON TABLE coinbase_app_rank_snapshots IS 'Historical snapshots of Coinbase App Store rankings for both finance category and overall';
