-- Migration: Create Coinbase App Store rank snapshots table
-- Description: Stores historical data of Coinbase's App Store rankings
-- Date: 2024-06-08

-- Create the table for storing rank snapshots
create table if not exists coinbase_app_rank_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz default now(),
  finance_rank integer,
  overall_rank integer,
  source text
);

-- Create an index for efficient querying by timestamp (newest first)
create index on coinbase_app_rank_snapshots (captured_at desc);

-- Add a comment to the table for documentation
comment on table coinbase_app_rank_snapshots is 'Historical snapshots of Coinbase App Store rankings for both finance category and overall';
